# Generated by Django 4.2.21 on 2025-10-25 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_activitylog'),
    ]

    operations = [
    ]
