# Generated by Django 4.2.21 on 2025-10-25 16:15

from django.db import migrations


def update_vehicle_status(apps, schema_editor):
    Vehicle = apps.get_model('core', 'Vehicle')
    # Update existing records
    Vehicle.objects.filter(status='Operational').update(status='Serviceable')
    Vehicle.objects.filter(status='Non-Operational').update(status='Unserviceable')


def reverse_update_vehicle_status(apps, schema_editor):
    Vehicle = apps.get_model('core', 'Vehicle')
    # Reverse the changes
    Vehicle.objects.filter(status='Serviceable').update(status='Operational')
    Vehicle.objects.filter(status='Unserviceable').update(status='Non-Operational')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_repair_repair_shop_alter_vehicle_status'),
    ]

    operations = [
        migrations.RunPython(update_vehicle_status, reverse_update_vehicle_status),
    ]
