# Generated by Django 4.2.21 on 2025-10-25 16:21

from django.db import migrations


def update_vehicle_status_to_new_system(apps, schema_editor):
    Vehicle = apps.get_model('core', 'Vehicle')
    # Update existing records to new status system
    Vehicle.objects.filter(status='Damaged').update(status='Under Repair')


def reverse_update_vehicle_status_to_new_system(apps, schema_editor):
    Vehicle = apps.get_model('core', 'Vehicle')
    # Reverse the changes
    Vehicle.objects.filter(status='Under Repair').update(status='Damaged')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20251026_0015'),
    ]

    operations = [
        migrations.RunPython(update_vehicle_status_to_new_system, reverse_update_vehicle_status_to_new_system),
    ]
