# Generated by Django 4.2.21 on 2025-10-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20251026_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fleet_card_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fleet Card Number'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gas_station',
            field=models.CharField(blank=True, max_length=200, verbose_name='Gas Station'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rfid_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='RFID Number'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rfid_type',
            field=models.CharField(blank=True, choices=[('Autosweep', 'Autosweep'), ('Easytrip', 'Easytrip')], max_length=20, null=True, verbose_name='RFID Type'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Serviceable', 'Serviceable'), ('Under Repair', 'Under Repair'), ('Unserviceable', 'Unserviceable')], default='Serviceable', max_length=20),
        ),
    ]
