# Generated by Django 4.2.21 on 2025-10-28 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_repair_disposal_type_repair_part_additional_info_and_more'),
    ]

    operations = [
        # Use raw SQL to fix the database schema
        migrations.RunSQL(
            # Forward SQL
            [
                "ALTER TABLE core_repair DROP COLUMN IF EXISTS additional_parts;",
                "ALTER TABLE core_repair DROP COLUMN IF EXISTS labor_cost;",
                "ALTER TABLE core_repair ADD COLUMN part_additional_info TEXT;",
                "ALTER TABLE core_repair ADD COLUMN part_quantity DECIMAL(10,2) NULL;",
                "ALTER TABLE core_repair ADD COLUMN part_unit VARCHAR(50) DEFAULT '';",
                "ALTER TABLE core_repair ADD COLUMN disposal_type VARCHAR(20) DEFAULT 'normal';",
            ],
            # Reverse SQL
            [
                "ALTER TABLE core_repair DROP COLUMN IF EXISTS disposal_type;",
                "ALTER TABLE core_repair DROP COLUMN IF EXISTS part_unit;",
                "ALTER TABLE core_repair DROP COLUMN IF EXISTS part_quantity;",
                "ALTER TABLE core_repair DROP COLUMN IF EXISTS part_additional_info;",
                "ALTER TABLE core_repair ADD COLUMN additional_parts TEXT;",
                "ALTER TABLE core_repair ADD COLUMN labor_cost DECIMAL(10,2);",
            ]
        ),
    ]
