# Generated by Django 4.2.21 on 2025-10-28 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_repair_disposal_type_repair_part_additional_info_and_more'),
    ]

    operations = [
        # Use raw SQL to fix the database schema
        # Note: part_additional_info, part_quantity, part_unit, and disposal_type 
        # are already added by migration 0013, so we only need to drop old columns
        migrations.RunSQL(
            # Forward SQL - only drop old columns that might exist
            [
                "ALTER TABLE core_repair DROP COLUMN IF EXISTS additional_parts;",
                "ALTER TABLE core_repair DROP COLUMN IF EXISTS labor_cost;",
            ],
            # Reverse SQL
            [
                "ALTER TABLE core_repair ADD COLUMN additional_parts TEXT;",
                "ALTER TABLE core_repair ADD COLUMN labor_cost DECIMAL(10,2);",
            ]
        ),
    ]
