# Generated by Django 4.2.21 on 2025-10-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_repair_parts_replaced_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Division',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='department',
            new_name='division',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, to='core.Division'),
        ),
    ]
