# Generated by Django 4.2.21 on 2025-10-29 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_repair_parts_replaced_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status_change_reason',
            field=models.TextField(blank=True, verbose_name='Status Change Reason'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Status Changed At'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Status Changed By'),
        ),
    ]
