# Generated by Django 4.2.21 on 2025-10-29 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_vehicle_status_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreInspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('repair', 'Repair'), ('pms', 'PMS')], max_length=10)),
                ('inspection_date', models.DateTimeField(auto_now_add=True)),
                ('engine_condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], max_length=10)),
                ('transmission_condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], max_length=10)),
                ('brakes_condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], max_length=10)),
                ('suspension_condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], max_length=10)),
                ('electrical_condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], max_length=10)),
                ('body_condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], max_length=10)),
                ('tires_condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], max_length=10)),
                ('lights_condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], max_length=10)),
                ('current_mileage', models.IntegerField()),
                ('fuel_level', models.CharField(choices=[('full', 'Full'), ('three_quarters', '3/4'), ('half', '1/2'), ('quarter', '1/4'), ('empty', 'Empty')], max_length=20)),
                ('issues_found', models.TextField(blank=True, help_text='List all issues found during inspection')),
                ('safety_concerns', models.TextField(blank=True, help_text='Any safety concerns identified')),
                ('recommended_actions', models.TextField(blank=True, help_text='Recommended actions before proceeding')),
                ('photos', models.JSONField(blank=True, default=list, help_text='List of photo file paths')),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pre_inspections', to=settings.AUTH_USER_MODEL)),
                ('inspected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_inspections', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_inspections', to='core.vehicle')),
            ],
            options={
                'verbose_name': 'Pre-Inspection Report',
                'verbose_name_plural': 'Pre-Inspection Reports',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='PostInspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('repair', 'Repair'), ('pms', 'PMS')], max_length=10)),
                ('inspection_date', models.DateTimeField(auto_now_add=True)),
                ('work_completed_satisfactorily', models.BooleanField(default=True)),
                ('quality_of_work', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('poor', 'Poor'), ('unsatisfactory', 'Unsatisfactory')], max_length=15)),
                ('timeliness', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('poor', 'Poor'), ('unsatisfactory', 'Unsatisfactory')], max_length=15)),
                ('cleanliness', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('poor', 'Poor'), ('unsatisfactory', 'Unsatisfactory')], max_length=15)),
                ('engine_condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], max_length=10)),
                ('transmission_condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], max_length=10)),
                ('brakes_condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], max_length=10)),
                ('suspension_condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], max_length=10)),
                ('electrical_condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], max_length=10)),
                ('body_condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], max_length=10)),
                ('tires_condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], max_length=10)),
                ('lights_condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], max_length=10)),
                ('test_drive_performed', models.BooleanField(default=True)),
                ('test_drive_distance', models.IntegerField(default=0, help_text='Distance driven during test (km)')),
                ('test_drive_notes', models.TextField(blank=True, help_text='Notes from test drive')),
                ('remaining_issues', models.TextField(blank=True, help_text='Any issues that remain unresolved')),
                ('future_recommendations', models.TextField(blank=True, help_text='Recommendations for future maintenance')),
                ('warranty_notes', models.TextField(blank=True, help_text='Warranty information if applicable')),
                ('photos', models.JSONField(blank=True, default=list, help_text='List of photo file paths')),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_post_inspections', to=settings.AUTH_USER_MODEL)),
                ('inspected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_inspections', to=settings.AUTH_USER_MODEL)),
                ('pre_inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_inspections', to='core.preinspectionreport')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_inspections', to='core.vehicle')),
            ],
            options={
                'verbose_name': 'Post-Inspection Report',
                'verbose_name_plural': 'Post-Inspection Reports',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.AddField(
            model_name='pms',
            name='post_inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pms_records', to='core.postinspectionreport'),
        ),
        migrations.AddField(
            model_name='pms',
            name='pre_inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pms_records', to='core.preinspectionreport'),
        ),
        migrations.AddField(
            model_name='repair',
            name='post_inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repairs', to='core.postinspectionreport'),
        ),
        migrations.AddField(
            model_name='repair',
            name='pre_inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='core.preinspectionreport'),
        ),
    ]
