# Generated by Django 5.2.7 on 2025-10-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_customuser_role_remove_repair_parts_replaced_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Serviceable', 'Serviceable'), ('Under Repair', 'Under Repair'), ('Unserviceable', 'Unserviceable'), ('For Disposal', 'For Disposal')], default='Serviceable', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('SEDAN', 'SEDAN'), ('SUV', 'SUV'), ('TRUCK', 'TRUCK'), ('PICK UP', 'PICK UP'), ('MOTORCYCLE', 'MOTORCYCLE'), ('CLOSE VAN', 'CLOSE VAN')], max_length=100),
        ),
    ]
