# Generated by Django 5.2.7 on 2025-11-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_change_replaced_parts_images_to_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preinspectionreport',
            name='driver_report_attachment',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='registration_document',
        ),
        migrations.AddField(
            model_name='preinspectionreport',
            name='driver_report_attachments',
            field=models.JSONField(blank=True, default=list, help_text='List of driver report attachment file paths'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='photos',
            field=models.JSONField(blank=True, default=list, help_text='List of vehicle photo file paths'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_documents',
            field=models.JSONField(blank=True, default=list, help_text='List of registration document file paths'),
        ),
        migrations.AlterField(
            model_name='postinspectionreport',
            name='replaced_parts_images',
            field=models.JSONField(blank=True, default=list, help_text='List of replaced parts image file paths', null=True),
        ),
    ]
